Algoritmo "circulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2020
Var
area, raio : real


Inicio
  Escreva ("Digite a raio do círculo: ")
  leia (raio)
  area <- (raio^2)*pi
  Escreva ("A área do círculo é de: ", area:3:3)


Fimalgoritmo