Algoritmo "SOMA"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2020
Var
x, y, soma : inteiro


Inicio
  Escreva ("Digite os dois números: ")
  leia (x)
  leia (y)
  soma <- x+y
  Escreva ("A soma destes números é: ", soma)


Fimalgoritmo