Algoritmo "tabuada"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/06/2020
Var
 N, i, total : inteiro


Inicio

  Escreva (" Deseja a tabuada para qual valor? ")
  leia (N)
  
  total <- 0
  para i de 1 ate 10 faca
  
    total <- N * i
    Escreval (n ," x", i, " =", total)

  fimpara


Fimalgoritmo